# Generated by Django 4.2.1 on 2023-09-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, null=True)),
                ('cep', models.CharField(max_length=250, null=True)),
                ('numero', models.CharField(max_length=250, null=True)),
                ('total', models.CharField(max_length=250, null=True)),
                ('avista', models.CharField(max_length=250, null=True)),
                ('entrada', models.CharField(max_length=250, null=True)),
                ('qtdx', models.CharField(max_length=250, null=True)),
                ('p12', models.CharField(max_length=250, null=True)),
                ('p24', models.CharField(max_length=250, null=True)),
                ('p36', models.CharField(max_length=250, null=True)),
                ('p48', models.CharField(max_length=250, null=True)),
                ('p60', models.CharField(max_length=250, null=True)),
                ('modulos', models.CharField(max_length=250, null=True)),
                ('mmarca', models.CharField(max_length=250, null=True)),
                ('inversor', models.CharField(max_length=250, null=True)),
                ('imarca', models.CharField(max_length=250, null=True)),
                ('conectores', models.CharField(max_length=250, null=True)),
                ('select', models.CharField(max_length=250, null=True)),
                ('preto', models.CharField(max_length=250, null=True)),
                ('vermelho', models.CharField(max_length=250, null=True)),
                ('garantia_modulos', models.CharField(max_length=250, null=True)),
                ('garantia_inversor', models.CharField(max_length=250, null=True)),
                ('garantia_estrutura', models.CharField(max_length=250, null=True)),
                ('garantia_demais', models.CharField(max_length=250, null=True)),
                ('garantia_por', models.CharField(max_length=250, null=True)),
                ('garantia_anos', models.CharField(max_length=250)),
            ],
        ),
    ]
