# Generated by Django 4.2.1 on 2023-09-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0002_orcamento_bairro_orcamento_cidade_orcamento_rua'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
