# Generated by Django 4.2.1 on 2023-09-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0003_orcamento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='data',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
