# Generated by Django 4.2.1 on 2023-09-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0004_alter_orcamento_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=250, null=True)),
                ('modelo', models.CharField(max_length=250, null=True)),
                ('watts', models.CharField(max_length=250, null=True)),
                ('eficiencia', models.CharField(max_length=250, null=True)),
                ('largura', models.CharField(max_length=250, null=True)),
                ('altura', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
