# Generated by Django 4.2.1 on 2023-09-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0005_placas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Placas',
        ),
    ]
