# Generated by Django 4.2.1 on 2023-11-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0006_delete_placas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Irradiacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_IR', models.IntegerField()),
                ('ANNUAL', models.FloatField()),
                ('JAN', models.FloatField()),
                ('FEB', models.FloatField()),
                ('MAR', models.FloatField()),
                ('APR', models.FloatField()),
                ('MAY', models.FloatField()),
                ('JUN', models.FloatField()),
                ('JUL', models.FloatField()),
                ('AUG', models.FloatField()),
                ('SEP', models.FloatField()),
                ('OCT', models.FloatField()),
                ('NOV', models.FloatField()),
                ('DEC', models.FloatField()),
            ],
        ),
    ]
