# Generated by Django 4.2.1 on 2023-11-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0007_irradiacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='consumo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='entrada_fin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_fin',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
