# Generated by Django 4.2.1 on 2023-11-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0008_orcamento_consumo_orcamento_entrada_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='id_modulo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
