# Generated by Django 4.2.1 on 2023-11-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0009_orcamento_id_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='cmtotal',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
