# Generated by Django 4.2.1 on 2023-11-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=250, null=True)),
                ('modelo', models.CharField(max_length=250, null=True)),
                ('watts', models.CharField(max_length=250, null=True)),
                ('eficiencia', models.CharField(max_length=250, null=True)),
                ('largura', models.CharField(max_length=250, null=True)),
                ('altura', models.CharField(max_length=250, null=True)),
                ('img', models.ImageField(upload_to='imagens/')),
            ],
        ),
        migrations.CreateModel(
            name='SolarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LON', models.CharField(max_length=100, null=True)),
                ('LAT', models.CharField(max_length=100, null=True)),
                ('NAME', models.CharField(max_length=100, null=True)),
                ('CLASS', models.CharField(max_length=100, null=True)),
                ('TATE', models.CharField(max_length=100, null=True)),
                ('ANNUAL', models.CharField(max_length=100, null=True)),
                ('JAN', models.CharField(max_length=100, null=True)),
                ('FEB', models.CharField(max_length=100, null=True)),
                ('APR', models.CharField(max_length=100, null=True)),
                ('MAY', models.CharField(max_length=100, null=True)),
                ('JUN', models.CharField(max_length=100, null=True)),
                ('JUL', models.CharField(max_length=100, null=True)),
                ('AUG', models.CharField(max_length=100, null=True)),
                ('SEP', models.CharField(max_length=100, null=True)),
                ('OCT', models.CharField(max_length=100, null=True)),
                ('NOV', models.CharField(max_length=100, null=True)),
                ('DEC', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
