# Generated by Django 4.2.1 on 2023-11-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solardata',
            name='TATE',
        ),
        migrations.AddField(
            model_name='solardata',
            name='sTATE',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
