# Generated by Django 4.2.1 on 2023-11-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placas', '0003_rename_state_solardata_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='solardata',
            name='MAR',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
