# Generated by Django 4.2.1 on 2023-11-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placas', '0004_solardata_mar'),
    ]

    operations = [
        migrations.AddField(
            model_name='solardata',
            name='CON',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
