# Generated by Django 4.2.1 on 2023-11-23 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placas', '0005_solardata_con'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solardata',
            name='CON',
        ),
    ]
