from django.db import models

class Orcamento(models.Model):
    nome = models.CharField(max_length=250, null=True)
    cep = models.CharField(max_length=250, null=True)
    rua = models.CharField(max_length=250, null=True)
    bairro = models.CharField(max_length=250, null=True)
    cidade = models.CharField(max_length=250, null=True)
    numero = models.CharField(max_length=250, null=True)
    total = models.CharField(max_length=250, null=True)
    avista = models.CharField(max_length=250, null=True)
    entrada = models.CharField(max_length=250, null=True)
    qtdx = models.CharField(max_length=250, null=True)
    p12 = models.CharField(max_length=250, null=True)
    p24 = models.CharField(max_length=250, null=True)
    p36 = models.CharField(max_length=250, null=True)
    p48 = models.CharField(max_length=250, null=True)
    p60 = models.CharField(max_length=250, null=True)
    modulos = models.CharField(max_length=250, null=True)
    mmarca = models.CharField(max_length=250, null=True)
    inversor = models.CharField(max_length=250, null=True)
    imarca = models.CharField(max_length=250, null=True)
    conectores = models.CharField(max_length=250, null=True)
    select = models.CharField(max_length=250, null=True)
    preto = models.CharField(max_length=250, null=True)
    vermelho = models.CharField(max_length=250, null=True)
    garantia_modulos = models.CharField(max_length=250, null=True)
    garantia_inversor = models.CharField(max_length=250, null=True)
    garantia_estrutura = models.CharField(max_length=250, null=True)
    garantia_demais = models.CharField(max_length=250, null=True)
    garantia_por = models.CharField(max_length=250, null=True)
    garantia_anos = models.CharField(max_length=250)
    data = models.DateField(auto_now=True, null=True)
    consumo = models.CharField(max_length=50, null=True)
    entrada_fin = models.CharField(max_length=50, null=True)
    valor_fin = models.CharField(max_length=50, null=True)
    id_modulo= models.CharField(max_length=10, null=True)
    cmtotal=models.CharField(max_length=50, null=True)

class Irradiacao(models.Model):
    ID_IR = models.IntegerField()
    ANNUAL = models.FloatField()
    JAN = models.FloatField()
    FEB = models.FloatField()
    MAR = models.FloatField()
    APR = models.FloatField()
    MAY = models.FloatField()
    JUN = models.FloatField()
    JUL = models.FloatField()
    AUG = models.FloatField()
    SEP = models.FloatField()
    OCT = models.FloatField()
    NOV = models.FloatField()
    DEC = models.FloatField()